### ISSUE TITLE
There's not a Glossary or Tutorial to the DDD newcomer

### ISSUE THREAD

**Issue by heltonbiker** [domainmap/app#2]
I am a huge enthusiast of DDD, but to be honest, I haven't studied or started it yet :o)

So when I saw the potential of DomainMap, with all those terms (those jargon terms), I got very excited, and looked around the App's page for some guidance about the expected meaning for those terms, and found none. Not even a tooltip ;o)

I think it would hugely increase the early adoption of the app, and the dissemination of TDD concepts in a rather curated way.

The terms I am referring to:

- Bounded Context
- Command Use Cases
- Query Use Cases
- Domain Services
- External Services
- Entities
- Value Objects
- Read Models
- Events
- Business Processes

(An actual example of mine: would MyServiceX would be considered a DomainService or an ExternalService? How can I know?)

**Comment by sapiens** [comment]
I'm very well aware of this. I've started writing a blog series DDD Decoded where I will talk about each concept with an example and linked to DMap and they will serve in a way as a tutorial. It's only [one post, ok, a trilogy](http://blog.sapiensworks.com/post/2016/07/14/DDD-Aggregate-Decoded-1) for now, but I plan to write around 2 per week with screenshots and all.

**Comment by heltonbiker** [comment]
Well, I'm gonna be in touch, and congrats by the initiative!

Should we change this issue status, then?
