### ISSUE TITLE
Github permissions

### ISSUE THREAD

**Issue by mattr** [domainmap/app#3]
I assume it's just an oversight, but is there a legitimate reason that this app needs **full access** to my account? (If it's not an oversight, perhaps something to indicate why it requires this level of access?)

![github_permissions](https://cloud.githubusercontent.com/assets/5474/17196593/fa5d9766-54a4-11e6-933d-01f158e508d7.PNG)

**Comment by sapiens** [comment]
It needs only the user name, I'll change it to ask for the minimum info.

**Comment by sapiens** [comment]
Done. It should ask for basic read only access from now on.
