### ISSUE TITLE
Private projects

### ISSUE THREAD

**Issue by sapiens** [domainmap/app#6]
I will add privacy if there's enough demand for it. It will be a paid feature though. Feel free to express your thoughts in this thread.

**Comment by RagingKore** [comment]
Hi Mike, I think DomainMap is indeed a very interesting tool, but the fact that it is not private is preventing me from using it and even suggesting it to my friends and colleagues. Just my 2 cents.

**Comment by wedneyyuri** [comment]
Hi @sapiens, +1 to @RagingKore. It's preventing us from using it. Also offering it as a paid feature would prevent us to discover your tool.
