### ISSUE TITLE
Loosen up required GitHub permissions

### ISSUE THREAD

**Issue by hanssens** [domainmap/app#7]
You've put up a great start with Domain Map Great, @sapiens. Keep it up! 

However, the required permissions "update all user data" for using Domain Map sound a bit harsh. Perhaps read-only info to basic profile info is enough?

![connection_with_domain_map](https://cloud.githubusercontent.com/assets/493382/24828260/b54bdd18-1c59-11e7-825a-9146ec1be06a.png)

**Comment by sapiens** [comment]
OK, this is pretty strange since I'm asking for minimum of permissions. The solution I found is  to revoke DomainMap's access then login again, granting access to the minimum permissions (read public info). I did that with my own account and seems to work properly now.

**Comment by hanssens** [comment]
Indeed, when I run it again today it requires only the public data (which is good!):

![authorize_domain_map](https://cloud.githubusercontent.com/assets/493382/24849826/d2505c5c-1dcd-11e7-93fe-d047916d9f2e.png)

Don't know what caused this, but this is just fine to me. Thanks.
